// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hsxhmpxrtfvydnfxtcbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeGhtcHhydGZ2eWRuZnh0Y2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NTM3MDcsImV4cCI6MjA3NzIyOTcwN30.NEe56Bn-TLjaiq542bGWcmoR2HLWbRq2cu08eaku8Dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);