// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://afgbyzukzpdgkpmnvihb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZ2J5enVrenBkZ2twbW52aWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNzQ0NzksImV4cCI6MjA4MzY1MDQ3OX0.pGmmR3on2pX0PYxxWNoxFnUdluG2QB2WU2j24-c0HAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);